Add downcasts page
rinatz/cpp-book pull request #12
Opened 2019-06-21 08:11 UTC by cpmrph

2019-06-21 15:51 UTC, km45 requested changes

2019-06-21 15:51 UTC, km45 commented on docs/appendix-downcasts.md
> +                     // base には存在しない領域 x_ を参照しようとして不正なメモリアクセスになる
```
Sub1* sub1 = dynamic_cast<Sub1*>(base);  // ダウンキャスト
```

の時点でキャストに失敗するため、
`sub1` は `base` のメモリ領域を指しておらず `nullptr` になります。

2019-06-23 04:31 UTC, cpmrph commented on docs/appendix-downcasts.md
> +                     // base には存在しない領域 x_ を参照しようとして不正なメモリアクセスになる
その通りですね。。。
コードの方は`static_cast`での例に変えつつ、全体の構成を見直しました。 7d53315

2019-06-23 06:37 UTC, km45 approved these changes

2019-06-24 04:05 UTC, merged