Explain each internal linkage is independent
rinatz/cpp-book pull request #32
Opened 2019-06-26 08:35 UTC by cpmrph

気の利いた見出しが思い浮かびませんでしたが、
定義が翻訳単位内で閉じていれば、重複違反にならないことを記載しました。

2019-06-26 13:08 UTC, km45 requested changes

2019-06-26 13:08 UTC, km45 commented on docs/ch04-04-internal-linkages.md
> +各々の内部リンケージを持たせて別のファイルから見えなくしていれば、別の定義として扱うことができます。
内部リンケージをもつのはシンボルなので、
「`各々に` 内部リンケージを持たせて」という表現がいいと思います。

2019-06-26 13:08 UTC, km45 commented on docs/ch04-04-internal-linkages.md
> +{
他の箇所に合わせて以下のように1行にして欲しいです。

```
int main() {
````

2019-06-27 01:56 UTC, cpmrph commented on docs/ch04-04-internal-linkages.md
> +各々の内部リンケージを持たせて別のファイルから見えなくしていれば、別の定義として扱うことができます。
b3ac764 ご提案いただいたとおりの文言に変えました

2019-06-27 01:57 UTC, cpmrph commented on docs/ch04-04-internal-linkages.md
> +{
直しました。 3acdc4e 
以前も同じ指摘を受けましたね…すみません。

2019-06-27 07:21 UTC, km45 approved these changes

2019-06-27 09:01 UTC, merged